# Generated by Django 5.0.6 on 2024-06-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_caducidad', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['-created'],
            },
        ),
    ]
